### PR TITLE
Empty-Stringify™ comment related feed tags

### LINKED ISSUE #21: Comments-Tags shown in Feed
```rss
<comments>
http://example.com/wordpress/?p=1#comments
</comments>
```
and

```rss
<wfw:commentRss>http://example.com/wordpress/?feed=rss2&p=1</wfw:commentRss>
<slash:comments>0</slash:comments>
```

are shown in http://example.com/wordpress/?feed=rss2

### PR DESCRIPTION
**Pull request by barryceelen**
Doesn’t fix #21 but at least removes the content of the affected tags.

### CODE REVIEW

**Comment by bueltge** [comment]
Nice, much shorter. Thanks a lot!

**Comment by barryceelen** [comment]
:+1:

**Comment by bueltge** [comment]
@barryceelen It is possible to write you via mail, german language? I have seen, that you work, live in Berlin.

**Comment by barryceelen** [comment]
Gerne! <a class="email" href="mailto:&#x62;&#x40;&#x72;&#x72;&#x79;&#x63;&#x65;&#x65;&#x6c;&#x65;&#x6e;&#x2e;&#x63;&#x6f;&#x6d;">&#x62;&#x40;&#x72;&#x72;&#x79;&#x63;&#x65;&#x65;&#x6c;&#x65;&#x6e;&#x2e;&#x63;&#x6f;&#x6d;</a>

**Pull request merged**
